### ISSUE TITLE
How to get Ledger XPUB ?

### ISSUE THREAD

**Issue by zebpayamarthakur** [bcoin-org/bledger#32]
I am trying to get XPUB for a ledger from below example. But I cannot get proper xpub for path m/44'/0'/0'.
https://github.com/bcoin-org/bledger/blob/08a9c0dcaa771aa02e609b2b2c4d880723937e71/examples/bcoin-getXPUBs.js

I have tried to get XPUB from HDPublic key from below functions -
xpubs[path].toJSON()
xpubs[path].xpubkey()

But XPUB generated from Mnemonic & bledger library for same path is different.
I have used https://iancoleman.io/bip39/ this website to generate XPUB from Mnemonic.

Need some urgent help.

**Comment by tynes** [comment]
This is the example that you want:
https://github.com/bcoin-org/bledger/blob/08a9c0dcaa771aa02e609b2b2c4d880723937e71/examples/bcoin-getPublicKey.js

The `bledger.getPublicKey` method will return a `bcoin.HDPublicKey` which is an extended public key

Make sure that you have your ledger initialized with the same mnemonic you are using with the website, although i don't recommend ever having a production mnemonic on your computer

**Comment by tynes** [comment]
Do you want the xpub string? You want `bcoin.HDPublicKey.xpubkey(network)`

**Comment by zebpayamarthakur** [comment]
Ledger which I am using it's only for testing purpose. So there is no issue of Mnemonic security.
I store production Mnemonic only on paper.

Yes I need XPUB string. 

I have tried bcoin.HDPublicKey.xpubkey(network). But it still gives me different XPUB string.

```
const path = `m/44'/0'/0'`;
const pubkeyHD = await ledgerBcoin.getPublicKey(path);
console.log(pubkeyHD.xpubkey());
```

I have also tried to get XPUB from Electrum & it is showing me same XPUB as from https://iancoleman.io/bip39/

Can you try to get XPUB string with bledger & compare that with Electrum XPUB.

Because it looks strange to me as Addresses & Public keys hex derived from HDPublicKey are correct & matches with this website https://iancoleman.io/bip39/

**Comment by nodar-chkuaselidze** [comment]
The difference between `getPublicKey` from bledger and some other libraries is that bledger is using calls that are listed in specification. 

Electrum is using python version of their library that has two methods related to getting public key: getWalletPublicKey and getPublicKey.

We currently support getWalletPublicKey which does not export parentFingerprint that's why XPUB constructed from it differs, but parentFinger is not used for non-hardened derivation that's why you will still generate correct public keys/addresses.

We can support another version that has `parentFingerprint` in it, that might be useful for many things.
